# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Nomer Kendaraan')),
                ('name', models.CharField(max_length=30, verbose_name='Nama Kendaraan')),
                ('driver', models.CharField(max_length=40, verbose_name='Sopir')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasitas Muatan')),
                ('photo', models.ImageField(blank=True, upload_to='car/%Y/%m/%d', verbose_name='Foto Kendaraan')),
            ],
        ),
    ]
